// Mocks generated by Mockito 5.1.0 from annotations
// in newsify_demo/test/features/news/domain/usecases/get_news_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:newsify_demo/core/error/failures.dart' as _i5;
import 'package:newsify_demo/features/news/domain/entities/news_entity.dart'
    as _i6;
import 'package:newsify_demo/features/news/domain/repositories/news_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [NewsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepo extends _i1.Mock implements _i3.NewsRepo {
  MockNewsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failures, _i6.NewsEntity>> getNews() =>
      (super.noSuchMethod(Invocation.method(#getNews, []),
          returnValue: Future<_i2.Either<_i5.Failures, _i6.NewsEntity>>.value(
              _FakeEither_0<_i5.Failures, _i6.NewsEntity>())) as _i4
          .Future<_i2.Either<_i5.Failures, _i6.NewsEntity>>);
}
